version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: asyl
      POSTGRES_PASSWORD: 20061960
      POSTGRES_DB: app_chat
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always

  django:
    build:
      context: ./backend/django_app
    volumes:
      - ./backend/django_app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]

  fastapi:
    build:
      context: ./backend/fastapi_app
    volumes:
      - ./backend/fastapi_app:/app
    ports:
      - "8001:8001"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1

volumes:
  postgres_data:
