version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: app_chat
      POSTGRES_USER: asyl
      POSTGRES_PASSWORD: 20061960
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Чтобы иметь доступ к БД с хоста (если нужно)

  django_app:
    build:
      context: ./backend/django_app
      dockerfile: Dockerfile
    command: sh -c "./wait-for-it.sh db:5432 -- python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend/django_app:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=app_chat
      - DB_USER=asyl
      - DB_PASSWORD=20061960
    depends_on:
      - db

  fastapi_app:
    build:
      context: ./backend/fastapi_app
      dockerfile: Dockerfile
    command: sh -c "./wait-for-it.sh db:5432 -- uvicorn main:app --host 0.0.0.0 --port 8001"
    volumes:
      - ./backend/fastapi_app:/app
    ports:
      - "8001:8001"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=app_chat
      - DB_USER=asyl
      - DB_PASSWORD=20061960
    depends_on:
      - db

volumes:
  postgres_data:
