version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: app_chat
      POSTGRES_USER: asyl
      POSTGRES_PASSWORD: 20061960
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django_app:
    build:
      context: .
      dockerfile: Dockerfile.django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/django_app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    command: uvicorn fastapi_app.main:app --host 0.0.0.0 --port 8001
    volumes:
      - ./backend/fastapi_app:/app
    ports:
      - "8001:8001"
    depends_on:
      - db

volumes:
  postgres_data:
