version: '3.9'

services:
  django:
    build: ./backend/django_app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend/django_app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DB_NAME=chat_db
      - DB_USER=chat_user
      - DB_PASSWORD=chat_password
      - DB_HOST=db
      - DB_PORT=5432

  fastapi:
    build: ./backend/fastapi_app
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      - DB_NAME=chat_db
      - DB_USER=chat_user
      - DB_PASSWORD=chat_password
      - DB_HOST=db
      - DB_PORT=5432

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: chat_db
      POSTGRES_USER: chat_user
      POSTGRES_PASSWORD: chat_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
